"""users table 2

Revision ID: 00a589b27d07
Revises: e91d2962394d
Create Date: 2023-06-18 19:51:44.054272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a589b27d07'
down_revision = 'e91d2962394d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_name', sa.String(length=33), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_second_name'), ['second_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_second_name'))
        batch_op.drop_column('second_name')

    # ### end Alembic commands ###
