"""add about_me and last_seen fields

Revision ID: 822cda32cdb7
Revises: b5827532686d
Create Date: 2023-11-05 19:40:35.069750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822cda32cdb7'
down_revision = 'b5827532686d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
