"""users table 3

Revision ID: eea812a7091f
Revises: 00a589b27d07
Create Date: 2023-06-18 19:52:46.217430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea812a7091f'
down_revision = '00a589b27d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_second_name')
        batch_op.drop_column('second_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_name', sa.VARCHAR(length=33), nullable=True))
        batch_op.create_index('ix_user_second_name', ['second_name'], unique=False)

    # ### end Alembic commands ###
